//
//  RecipeModel.swift
//  RecipeSaver
//
//  Created by Puhiza Tmava on 20.9.23.
//

import Foundation

enum Category: String, CaseIterable, Identifiable {
    var id: String {self.rawValue}
    case breakfast = "Breakfast"
    case soup = "Soup"
    case salad = "Salad"
    case appetizer = "Appetizer"
    case main = "Main"
    case dessert = "Dessert"
    case snack = "Snack"
    case drink = "Drink"
}

struct Recipe: Identifiable{
    let id = UUID()
    let name: String
    let image: String
    let description: String
    let ingredients: String
    let directions: String
    let category: Category.RawValue
    let datePublished: String
    let url: String
}
extension Recipe {
    static let all: [Recipe] = [
    Recipe(name: "Vegan Palacinky", image: "https://www.zasadnezdrave.cz/wp-content/uploads/2015/06/rawbananovepalacinky-bcg-01.jpg", description: "This famous Czech dessert is traditionally made with eggs, milk, and oil, but our vegan, oil-free version is packed full of delicious flavors that will satisfy your cravings without the unhealthy ingredients. The secret to pillow-soft vegan crepes? Sparkling water! This key addition makes the batter extra fluffy so each bite is light and delicate.", ingredients: "¾ cup whole wheat flour, 2 tablespoons brown rice flour, ½ cup sparkling water, ¼ cup unsweetened, unflavored plant-based milk, 1 tablespoon date syrup or pure maple syrup, plus more for serving, Pinch sea salt, 1 cup thinly sliced strawberries, 1 cup fresh blueberries", directions: "In a blender combine the first six ingredients (through salt). Cover and blend until smooth. Heat a nonstick crepe pan over medium. Ladle ¼ cup batter in middle of the pan; use the back of the ladle to spread batter into a 6-inch crepe. Cook 2 to 3 minutes or until crepe easily releases from pan (no need to flip it). While crepe is still in the pan, place a few strawberry slices and some blueberries on one side of crepe. Roll crepe over the fruit and continue rolling to the other side. Remove from pan. Repeat with remaining batter and fruit. Lightly drizzle crepes with additional syrup. Serve immediately.", category: "Breakfast", datePublished: "2023-05-06", url: "https://www.forksoverknives.com/recipes/vegan-breakfast/vegan-palacinky-czech-sweet-crepes/"),
    Recipe(name: "Chocolate Vegan Flan", image: "https://naturalgoodness.blog/wp-content/uploads/2020/04/vegan_flan_with_fruits.jpg", description: "This eggless chocolate flan recipe is a surefire winner for your next fiesta. Sweet potato puree takes the place of sweetened condensed milk to create a luscious creamy texture that melts in your mouth with every spoonful. Agar powder (a vegan setting agent derived from seaweed) ensures you still get the traditional jiggly texture while cocoa powder infuses everything with chocolatey goodness. ", ingredients: "1 15-oz. can sweet potato puree, ½ cup date syrup or pure maple syrup, plus more for serving, ¼ cup unsweetened cocoa powder, 1 tablespoon cashew butter or any other nut butter, 1½ teaspoons pure vanilla extract, 1 teaspoon agar powder, 1 tablespoon arrowroot powder, Chopped strawberries, for garnish", directions: "In a blender combine the first six ingredients (through agar powder) and 1½ cups water. Cover and blend until smooth and creamy. Transfer mixture to a small saucepan. Bring to a simmer over medium. Simmer, uncovered, 10 to 12 minutes or until agar is fully dissolved, stirring frequently to keep mixture from scorching. In a small bowl whisk together arrowroot powder and 1 tablespoon water. While stirring, add mixture to saucepan. Cook 4 to 5 minutes more or until mixture thickens slightly, stirring constantly. Remove from heat; let stand 20 minutes to cool, stirring occasionally for even cooling and thickening. Place a silicone cupcake tray or 10 individual molds on a tray. Pour ⅓ cup of the mixture into each mold. Transfer the tray to the refrigerator. Chill 1 hour or until set. To serve, flip the molds and press flans out onto individual dessert plates. Drizzle with additional date syrup and garnish with strawberries.", category: "Dessert", datePublished: "2022-01-02", url: "https://www.forksoverknives.com/recipes/vegan-desserts/chocolate-vegan-flan/"),
    Recipe(name: "Layered Black Rice Salad", image: "https://assets.epicurious.com/photos/54b018456429c4a41c09202b/4:3/w_811,h_608,c_limit/51160880_black-rice-salad_1x1.jpg", description: "Be prepared for an abundance of “oohs” and “aahs” when you present this multicolor black rice salad at your next dinner party. The chewy rice creates eye-catching bands of deep purple grains that are stacked between crunchy carrots, tangy red onion, hearty edamame, and aromatic herbs.", ingredients: "2 tablespoons rice vinegar, 2 tablespoons lime juice, 2 tablespoons reduced-sodium soy sauce, 2 teaspoons pure maple syrup, 1 teaspoons sriracha sauce, ½ teaspoon red pepper flakes, 4 cups cooled cooked black rice, 2 cups fresh or thawed frozen edamame, 2 cups shredded carrots, 1 medium red bell pepper, cut into thin strips, ½ cup thinly sliced halved red onion, 1 cup coarsely chopped fresh herbs, such as mint, Thai basil, and/or cilantro, 2 tablespoons sesame seeds, toasted, Lime wedges", directions: "For Spicy Soy Vinaigrette, in a small bowl whisk together brown rice vinegar, lime juice, reduced-sodium soy sauce, maple syrup, sriracha sauce, crushed red pepper, and 2 tablespoons water. Dressing can be refrigerated until ready to serve. In a large glass bowl, layer half each of the rice, edamame, carrots, bell pepper, onion, fresh herbs, Spicy Soy Vinaigrette, and sesame seeds. Repeat layers. Serve with lime wedges and garnish with additional fresh herbs.", category: "Salad", datePublished: "2021-04-05", url: "https://www.forksoverknives.com/recipes/vegan-salads-sides/layered-black-rice-salad/"),
    Recipe(name: "Pineapple Ginger Smoothie", image: "https://usa.fage/sites/usa.fage/files/Recipe_Tiles_600x420_0016_Fage_Sept20_Plain_Immune_Lemon_Hero_0456_RTF.jpg", description: "Take your taste buds on a tropical vacation with this cold and creamy concoction that tastes like sunshine in a glass. Blended banana and pineapple are infused with the invigorating flavors of ginger and turmeric so you end up with a slushy treat that’s halfway between a golden milk latte and a tiki drink.", ingredients: "1 banana, sliced and frozen, 1 cup unsweetened, unflavored plant-based milk, 2 tablespoons quick-cooking oats (see tip, recipe intro), 8 oz. frozen pineapple (about 1 cup), ½ teaspoon grated fresh ginger, ¼ teaspoon ground turmeric", directions: "Line a baking sheet with parchment paper. Freeze bananas on prepared baking sheet for at least 2 hours. In a high-powered blender (or food processor), combine plant milk, quick-cooking oats, frozen bananas and pineapple, ginger, and turmeric. Blend until smooth. Pour into a glass and serve.", category: "Drink", datePublished: "2023-05-05", url: "https://www.forksoverknives.com/recipes/vegan-snacks-appetizers/pineapple-ginger-smoothie/"),
    Recipe(name: "Pinto Bean Spread", image: "https://i.pinimg.com/originals/d4/dd/35/d4dd3577108e4c8769e327a1122e88f3.png", description: "Chef Walter grew up eating pinto beans all the time, and he loves this bean spread served on sandwiches, toast, and with freshly cut vegetables for a family gathering or celebration. I use this spread on my toast in the morning for a quick, nutritious breakfast. ", ingredients: "1 cup peeled garlic cloves, 1 pinch dried thyme, Sea salt, to taste, Freshly ground black pepper, to taste, 2 15.5-oz. cans no-salt-added pinto beans (3 cups),¼ cup lemon juice, 1 teaspoon mild New Mexico red chile powder (optional)", directions: "For Blackened Garlic, heat a small cast-iron skillet over high. Add garlic cloves to hot skillet. Cook 3 minutes or until garlic starts to blacken. Cook and stir 3 minutes more or until garlic is lightly blackened on all sides. Add dried thyme and a pinch each of sea salt and freshly ground black pepper; toss to coat. Transfer to a cutting board; let cool. Mince garlic. Drain pinto beans, reserving liquid. Rinse and drain beans. If you like, reserve a few beans for garnish. In a food processor combine beans and 3 tablespoons Blackened Garlic; process until smooth. Add lemon juice and chile powder (if using). Season with salt and black pepper. Process until creamy. (There should be no lumps.) Add reserved liquid from the pinto beans, 1 to 2 tablespoons at a time, as needed to reach desired texture. Top with reserved beans (if using) and additional chile powder. Serve Pinto Bean Spread immediately or store in an airtight container in the refrigerator up to 3 days. Store leftover Blackened Garlic in a separate airtight container in the refrigerator up to 4 days.", category: "Snack", datePublished: "2023-04-03", url: "https://www.forksoverknives.com/recipes/vegan-snacks-appetizers/pinto-bean-spread/"),
    Recipe(name: "Hannah Che’s Vegan Bao Buns", image: "https://content.hy-vee.com/remote.axd/3f4c2184e060ce99111b-f8c0985c8cb63a71df5cb7fd729edcab.ssl.cf2.rackcdn.com/media/19145/steamedbaobuns.jpg?v=1&mode=crop&width=800&height=640&upscale=false", description: "Soft steamed bread stuffed generously with a piping hot, flavorful medley of veggies—it doesn’t get much better than bao. These popular Chinese buns are incredibly versatile in terms of their filling, which is why we’ve included three different savory options that will make you salivate.", ingredients: "1 tablespoon pure cane sugar, 1¼ teaspoons active dry yeast, 3 cups white whole wheat flour (360 grams), plus more for dusting, 1 teaspoon baking powder, 1 bao bun filling of your choice", directions: "In a large bowl combine sugar, yeast, and 1¼ cups warm water (105°F to 115°F); stir to dissolve. Let stand 5 to 10 minutes or until small bubbles appear on the surface. Add flour and baking powder; stir with a fork or pair of chopsticks until large flakes form. Using your hands, knead mixture vigorously until a smooth, elastic dough forms, about 15 minutes. Return dough to bowl; cover with a damp clean kitchen towel or plate, and let rise in a warm place for 60 to 90 minutes, until dough doubles in size,. Meanwhile, prepare desired filling. On a clean, lightly floured surface, knead dough vigorously 5 minutes or until there are no air bubbles and dough is very smooth. Shape dough into a 1½-inch-thick log. Slice into 20 equal pieces (about the size of golf balls). Cut twenty 4-inch squares of parchment paper.", category: "Main", datePublished: "2022-07-08", url: "https://www.forksoverknives.com/recipes/vegan-baked-stuffed/hannah-che-vegan-bao-buns/"),
    Recipe(name: "Sopa de Nopales", image: "https://cdn2.cocinadelirante.com/sites/default/files/images/2019/12/receta-de-sopa-de-nopales-con-chile-guajillo.jpg", description: "When boiled, nopales (cactus) take on a viscous quality that works well in soups, allowing their flavor to meld with other ingredients without becoming mushy. This delicious soup adds sweet corn, hearty black beans, and juicy green peas to the mix so each bite is packed full of filling Southwestern flavors.", ingredients: "3 cups 1-inch pieces cleaned nopales (about 14 oz.) (see tip, below), 3 scallions, ½ cup finely chopped onion, 10 to 12 cloves garlic, minced, Freshly ground black pepper, 2 cups chopped tomatoes, 1 teaspoon dried Mexican oregano, crushed, 1 15-oz. can black beans, rinsed and drained (1½ cups), 1 cup fresh or frozen corn, 1 cup fresh or frozen green peas, Sea salt, to taste, Crushed red pepper (optional), 1 lemon, cut into thin wedges", directions: "In a large saucepan combine nopales, two of the scallions, and 3 cups water. Bring to boiling; reduce heat. Cover and simmer 20 minutes or until nopales turn dull olive green. Remove and discard scallions. Meanwhile, in a large skillet cook onion, garlic, and a pinch black pepper over medium 10 minutes or until onion is translucent, adding water, 1 to 2 tablespoons at a time, as needed to prevent sticking. Add tomatoes and oregano; cook 5 to 7 minutes more or until tomatoes are tender. Transfer sautéed vegetables to saucepan with nopales. Stir in beans, corn, peas, and 1 cup water. Season with salt and black pepper. Cook 10 minutes to blend flavors. Meanwhile, thinly slice remaining scallion. Garnish soup with scallion and, if desired, crushed red pepper. Serve with lemon wedges.", category: "Soup", datePublished: "2023-08-08", url: "https://www.forksoverknives.com/recipes/vegan-soups-stews/sopa-de-nopales/")]
}
